### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#193]
- [ ] Additional flag "API user": "0" for every user having registered via the MiBi-Portal client; "1" for user accounts intended to be used by machines; can be changed by admin/developer only
- [ ] User tokens and API user tokens (validity length, method of how to extend validity)
- [ ] API calls per minute
- [ ] Log files (include what? how long? alerts to admin? making use of information?
