### ISSUE TITLE
Use condensed ZSP list instead of extended ZSP list

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#253]
As a product owner I would like to use the condensed ZSP list consisting of 15-20 rows with several comma separated values in each cell instead of the extended ZSP list with 50.000 unique ZSP combinations.
In the condensed ZSP list there are several ADV codes summarised using "x". E.g. "30xxxxx" represents theoretically up to 100.000 different codes which would be one row in the condensed ZSP list and 100.000 rows in the extended ZSP list. If new ADV codes are published during the year the condensed list is automatically valid while one would need to produce the extended list anew.

Condensed ZSP list:
[mps253_Condensed ZSP list.xlsx](https://github.com/user-attachments/files/17186644/mps253_Condensed.ZSP.list.xlsx)

Technical note: Make ZSP check DB friendly.

In preparation for user data persistence and uploading data by product owner we decided to extend this ticket to also implement necessary features to amend the ddd-patterns already used by server with data validation logic and domain specific objects. So actually implement the features that represent the domain.
So the ticket is divided into following sub-tasks:
- [ ] General domain objects
  - [x] abstract Entity/AggregateRoot
  - [x] abstract Value Object
  - [x] abstract Repository, Persistence and data mappers
  - [x] Result object to represent domain failures
  - [ ] Handling of domain failures and abstract Error
  - [x] abstract Value Collections
  - [x] common input guards for primitive types
  - [ ] Unit test for abstract domain objects
- [x] Domain objects for adv-codes and wrapper for old code
- [ ] Domain objects for the ZSP
- [ ] Persistence module for reading condensed ZSP from file
- [ ] Service for validating sample against ZSP
- [ ] Service for identifying if a sample might be in a ZSP
- [ ] Integrating new code into old code base
- [ ] Remove old code and clean up
- [ ] Unit tests for ZSP features

- #276 
- #277 
- #278 
- #280 
- #275 
- #273 
- #274 
- #279 
- #272

**Comment by afalenski** [comment]
A condensed CSV list is used since July 2025.
Done.
